pipeline:

  frontend:      
    image: java:8
    image: maven:3.5.3
    commands:
      - mvn org.codehaus.mojo:versions-maven-plugin:2.2:set  -Dmaven.test.skip=true -DOCKER_HOST=35.192.55.117  -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn  -U -DnewVersion=1.0.3
      - mvn clean -B -e -U deploy -Dmaven.test.skip=false  -Dmaven.test.skip=true -DOCKER_HOST=35.192.55.117 -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn  -P openshift
      - mvn io.github.stackinfo:stackinfo-maven-plugin:0.2:prepare -Dmaven.test.skip=true -DOCKER_HOST=35.192.55.117 -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn 
      - ls -ltr
      - ls -ltr ./target
      
     
     
